unbind r
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

set -g prefix C-s

set -g default-terminal "screen-256color"
set -as terminal-overrides ",xterm-256color:Tc"
set -ga terminal-overrides ",xterm-256color:Tc"

# split panes using = and -
bind = split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Switch panes like vim
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# turn mouse support on
set-option -g mouse on

# start with window and pane number 1
set-option -g base-index 1
set-option -g pane-base-index 1

# allow manual renaming windows
set-window-option -g allow-rename off

# redimensiona painel with Vim keys (no prefix)
bind-key -n C-S-Left resize-pane -L 1
bind-key -r H resize-pane -L 1

bind-key -n C-S-Right resize-pane -R 1
bind-key -r L resize-pane -R 1

bind-key -n C-S-Down resize-pane -D 1
bind-key -r J resize-pane -D 1

bind-key -n C-S-Up resize-pane -U 1
bind-key -r K resize-pane -U 1

set -g status-position bottom 

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'

set -g @dracula-colors " white='#f8f8f2' gray='#44475a' dark_gray='#282a36' light_purple='#bd93f9' dark_purple='#6272a4' cyan='#8be9fd' green='#50fa7b' orange='#ffb86c' red='#ff5555' pink='#ff79c6' yellow='#f1fa8c' "
set -g @dracula-plugins "cpu-usage ram-usage"
set -g @dracula-cpu-usage-colors "green dark_gray"
set -g @dracula-ram-usage-colors "dark_purple dark_gray"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
